apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: mysql-user-creds
    envs:
      - .env.mysql
resources:
  - mysql/mysql-volume.yaml
  - mysql/mysql-deployment.yaml
  - nginx/nginx-code-volume.yaml
  - nginx/nginx-configMap.yaml
  - nginx/nginx-service.yaml
  - nginx/nginx-deployment.yaml