apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: mysql-user-creds
    envs:
      - .env.mysql
  - name: ghcr-secret
    files:
      - ~/.docker/config.json
    type: kubernetes.io/dockerconfigjson
resources:
  - mysql/mysql-volume.yaml
  - mysql/mysql-deployment.yaml