name: Build images
on:
  workflow_run:
    branches: [main]
    workflows: ["CI test"]
    types:
      - completed

jobs:
  build-nginx-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t nginx -f ./docker/nginx/Dockerfile .
      - name: Login to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/nginx
          VERSION=latest

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag nginx $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
  build-php-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t php -f ./docker/php/Dockerfile .
      - name: Login to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image to GHCR
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/php
          VERSION=latest

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag php $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION