name: Make new app version
on:
  create:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IMAGE_ID: ghcr.io/${{ github.repository }}/php
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get commit sha
        run: echo "BUILD_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Login to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image by commit sha and tag with the version number
        run: |
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $IMAGE_ID:$BUILD_SHA $IMAGE_ID:$RELEASE_VERSION
          docker push $IMAGE_ID:$RELEASE_VERSION