name: CI test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: composer install -q --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Check code styles
        run: composer phpcs
      - name: Run unit tests
        run: composer tests